### PR TITLE
Adds support for tags

### PR DESCRIPTION
**Pull request by CraigHarley**

### CODE REVIEW

**Comment by romanzipp** [comment]
Could you give me a brief description, why you need an additional field, and why it should be called "tags"?

**Comment by CraigHarley** [comment]
This doesn't work unfortunately, but the intention was to use the `tags` horizon uses:

Screenshot 2019-08-21 at 11 13 46

Below the job name you can see the tags, which come from the function on the job called `tags` like this:
```
    /**
     * Get the tags that should be assigned to the job.
     *
     * @return array
     */
    public function tags(): array
    {
        return [
            'blah blah blah',
            'foo foo foo'
        ];
    }
```

**Comment by CraigHarley** [comment]
I'm guessing it doesn't work because we only have access to the `Job` class, rather than the class the trait is applied to.

**Comment by romanzipp** [comment]
I don't believe the tags should receive on own database field. You can use the `queueData()` method for this.

**Pull request closed without merging**
