### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected a dependency for the `laravel/framework`. Unless you have a special requirement for depending on the entire Laravel framework, it's recommended to add dependencies for the specific `illuminate` packages instead.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/Laravel-Queue-Monitor.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "romanzipp/laravel-queue-monitor": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by jonnott** [comment]
@romanzipp Laravel 11 release day is today. Can this be merged and a new version tagged, please? 👍

**Comment by jonnott** [comment]
@romanzipp Thanks for merging. Anything I could help with in order to get a L11.x-compatible release tagged?

**Comment by romanzipp** [comment]
Tagged in [5.2.0](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/5.2.0), had to fix some issues with backwards compatibility and upgrade migrations

**Comment by jonnott** [comment]
> Tagged in [5.2.0](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/5.2.0), had to fix some issues with backwards compatibility and upgrade migrations

Amazing, thanks. Any chance you can mark it as a proper 'release', so others get to know there's now a Laravel 11.x-compatible version available?

**Pull request merged**
